#!/bin/bash

FILE=ga
SIMFILE=ga-sim

echo "#!/bin/bash" > $FILE
echo "# !!! auto generated by make-ga-script.sh !!!" >> $FILE
echo "emacs --quick --script $(pwd)/src/ga-main.el" '--wd $(pwd) $@' >> $FILE

echo "#!/bin/bash" > $SIMFILE
echo "# !!! auto generated by make-ga-script.sh !!!" >> $SIMFILE
echo "emacs --no-init-file --quick --no-site-lisp --background-color gray14 --no-bitmap-icon --load $(pwd)/src/ga-run-simulator.el" ' $(pwd) $@' >> $SIMFILE

