#lang racket ;; -*- lexical-binding: t -*-

(require compatibility/defmacro
         "../common.rkt"
         "../compiler/compile.rkt"
         "../compiler/assemble.rkt"
         "../el.rkt")

(define compiler-tests
  '(("node 1 " (1 ))
    ("node 1 2" (1 ("@p" "." "." ".")
                   2))
    ("node 1 22 +" (1 ("@p" "+" "." ".")
                      22))
    ("node 1 @ @ @ @ @ @" (1 ("@" "@" "@" ".")
                             ("@" "@" "@" ".")))
    ("node 1 dup dup dup dup @p @p @p @p" (1 ("dup" "dup" "dup" "dup")
                                             ("@p" "@p" "@p" "@p")))
    ("node 1 0 if dup dup then over over" (1 ("@p" "if" 3 ".")
                                             0
                                             ("dup" "dup" "." ".")
                                             ("over" "over" "." ".")))
    ("node 1 up down left right" (1 ("@p" "@p" "@p" "@p") 325 277 373 469))
    ("node 2 up down left right" (2 ("@p" "@p" "@p" "@p") 325 277 373 469))
    ("node 101 up down left right" (101 ("@p" "@p" "@p" "@p") 325 277 373 469))
    ("node 1 north east south west" (1 ("@p" "@p" "@p" "@p")
                                       277 373 325 469))
    ("node 2 north east south west" (2 ("@p" "@p" "@p" "@p")
                                       277 469 325 373))
    ("node 101 north east south west" (101 ("@p" "@p" "@p" "@p")
                                           325 373 277 469))
    ("node 102 north east south west" (102 ("@p" "@p" "@p" "@p")
                                           325 469 277 373))
    ("node 1 : word dup ; : word2 + + + ; word word2" (1 ("dup" ";" "." ".")
                                                         ("+" "+" "+" ";")
                                                         ("call" 0 "." ".")
                                                         ("call" 1 "." ".")))
    ("node 1 ---u --l- --lu -d--" (1 ("call" 325 "." ".")
                                     ("call" 373 "." ".")
                                     ("call" 357 "." ".")
                                     ("call" 277 "." ".")))
    ;;("node 1 " (1 ))
    ))

(define (fix-word word)
  (when  (vector? word)
    (set! word (vector->list word)))

  (if (list? word)
      (map (lambda (x) (if (equal? x false) "." x))
           word)
      word))

(define (trim-mem mem)
  (map fix-word
       (filter (lambda (x) (not (or (equal? x (vector false false false false))
                                    (equal? x false))))
               (vector->list mem))))


(define (run-compiler-tests)
  (define code false)
  (define compiled false)
  (define compiled-hash false)
  (define node false)
  (define expect false)
  (define mem false)
  (define ok true)
  (for ((test compiler-tests))
    (set! code (car test))
    (assert (string? code))
    (set! compiled (aforth-compile code))
    (set! compiled-hash (make-hash))
    (for ((node (compiled-nodes compiled)))
      (hash-set! compiled-hash (node-coord node)
                 (trim-mem (vector-copy (node-mem node)))))
    (for ((x (cdr test)))
      (set! node (car x))
      (set! expect (cdr x))
      (if (hash-has-key? compiled-hash node)
          (set! mem (hash-ref compiled-hash node))
          (error (rkt-format "Expected node '~a' results from test code \"~a\"\n" node code)))
      (when (not (equal? mem expect))
        (printf "failed: '~a'\n" code)
        (printf "     got: ~a\n" mem)
        (printf "expected: ~a\n\n" expect)
        (set! ok false))))
  ok)

(run-compiler-tests)
